### ISSUE TITLE
在fragment中画多条线会出现控制针，排除生命周期问题，在onresume方法里使用也是空指针

### ISSUE THREAD

**Issue by riseLishan** [whataa/SuitLines#27]
java.lang.NullPointerException: Attempt to read from field 'float android.graphics.RectF.left' on a null object reference
                                                                                    at tech.linjiang.suitlines.SuitLines.buildPaintColor(SuitLines.java:811)
                                                                                    at tech.linjiang.suitlines.SuitLines.access$1000(SuitLines.java:58)
                                                                                    at tech.linjiang.suitlines.SuitLines$LineBuilder.build(SuitLines.java:1362)
                                                                                    at com.handtv.jbw.clevermediation.view.fragment.HomeFragment.init(HomeFragment.java:183)
                                                                                    at com.handtv.jbw.clevermediation.view.fragment.HomeFragment.initView(HomeFragment.java:156)
                                                                                    at rxfamily.view.BaseFragment.onCreateView(BaseFragment.java:69)
                                                                                    at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192

**Comment by whataa** [comment]
已修复
