### ISSUE TITLE
画多条线时崩溃

### ISSUE THREAD

**Issue by androidthinker** [whataa/SuitLines#8]
Caused by: java.lang.NullPointerException: Attempt to read from field 'float android.graphics.RectF.left' on a null object reference
                                                                          at tech.linjiang.suitlines.SuitLines.buildPaintColor(SuitLines.java:776)
                                                                          at tech.linjiang.suitlines.SuitLines.access$1000(SuitLines.java:58)

**Comment by whataa** [comment]
这个问题和 #7  类似，都是在View未完全加载时调用某些api造成的（例如在onCreate时就设定line的颜色、填充数据等），请按正确方式使用，感谢反馈。
